const notes = {
    "title": "Notes",
    "body": `
            24.02.2025<br>
            The first meeting was extremely interesting. We spoke about May the opposite befall me, exploring new ways to implement participation in the game, and the other ideas.<br>
            I&rsquo;m now tasked with the most difficult job: choosing which idea to develop.<br>
            I have two approaches to the problem: what in Italian I would call &ldquo;seguire la pancia&rdquo; (following my gut), and a more analytical choice.<br>
            Starting with the analytical approach: continuing May the opposite befall me is beneficial in many ways, especially because I want to correct the things that dissatisfy me. On the other hand, it&rsquo;s a project that, although passionate to me, is not lined with my idea of videogames.<br>
            The second proposal (the game bible) is a good way to finally experiment with my ideas about participation in games. This would be a good testing ground to confirm or falsify my theories. On the other hand, the idea is very vague, and the project would need a lot of thinking which may slow me down.<br>
            The third proposal (collection of short stories) has many different possibilities to explore the topics. The aspect of self-contained stories that are somewhat connected is very interesting, but also very complex to do effectively. I also like the idea of creating a page to collect all the texts, where everyone can read them in the same place, maybe with design interactions.<br>
            My gut tells me I should choose the third proposal.<br>
            Summary: the first proposal is interesting for a variety of ways to develop the topic and the possibility of compiling all short stories in a single place. Although difficult to properly connect the stories. My gut tells me I should go for this project, despite other proposals&rsquo; interesting aspects. Maybe some sleep will help me to decide. In any case, I&rsquo;m already thinking of prompts for the texts, this could mean that I&rsquo;ve already chosen.<br>
            <br>
            25.02.2025<br>
            Apparently, we&rsquo;ll have a 1/14 possibility of winning the PAX Award (which is about 7.4%). It&rsquo;s not good, it&rsquo;s not bad. I&rsquo;m probably writing this because I&rsquo;m trying to convince myself to continue the project. Noah and Lendi will work on it at some point, at least to make it good enough to be put on itch.io. I don&rsquo;t kwon how I feel about it. Again, I&rsquo;m not satisfied with my work. But it&rsquo;s a first time.<br>
            Anyway, how can I make the short stories both interesting and consistent? I probably need to decide first the whole context of the story. Meaning that I must find a series of events and characters that influenced the story until the present moment. Maybe those events are the memories that the protagonist explores. Those stories may come from a little bookshelf they have in the pod. They read those stories repeatedly to the point that, when they forgot about the bookshelf, they ended up confusing those stories with their memories.<br>
            <br>
            26.02.2025<br>
            I have a terribly complex idea. But achieving it would mean making this project very interesting to develop.<br>
            The premise is that someone is trying to remember who they were from different memories. But at some point, those memories will end. What if they involuntarily begin to mix up those memories? First, a few details are taken from other stories and placed elsewhere. The effect gradually increases until it is completely evident. This is an interesting way to problematize isolation even more: those memories may not have been reliable from the start.<br>
            I want readers to think &ldquo;I&rsquo;ve already read this&rdquo; or &ldquo;that&rsquo;s not how it went&rdquo;, until the thought is &ldquo;this is not working anymore&rdquo;.<br>
            In the case that I develop the project on html, I could show all the texts floating like thoughts. Once the reader starts reading, the texts start to change, mixing texts that the reader read to others. This means that unread texts are modified before they can be read. The available texts start to decrease because multiple texts are mixed into single texts. In the end, one text is available where the protagonist realizes what is happening, thus starting all over (the reader would have to refresh the page).<br>
            If I ever decide to develop the project on a webpage, I could make the texts titles floating and clickable (as thoughts?). Once the reader starts, unread texts start to change and mix with others, modifying them before they can be read. Available texts slowly decrease as multiple stories mix into single stories. The remaining texts become increasingly more incoherent until only one remains. The last one could be a monologue of the protagonist realizing that the method is not working or, even worse, the premise once again. In any case, to read all possible texts, the reader must restart and try again. I want readers to experience the same sense of confusion and loss that the protagonist feels.<br>
            <br>
            <br>
            28.02.2025<br>
            Watching Cloud Atlas made me think about this: if the core of the film is that every life is in some way connected and influenced by people&rsquo;s actions, bad and good, then my story should be its antithesis. There is no connection between the protagonist and the memories that they hold. Their situation is simply too distant from reality, both physically and spiritually (although I don&rsquo;t think I want to include a spiritual thematic, I point it out just to be complete). But I will develop this concept further when I am done writing the premise, which is what I will do now.<br>
            <br>
            Reading Memorie di un viaggiatore spaziale was my next activity on the list, since judging from the premise I think it could really help me to structure the project. I decided to watch Cloud Atlas instead of reading it for brevity&rsquo;s sake (I wanted to start writing at least the premise to concretize it), but I may reconsider.<br>
            Regarding my statement on the project&rsquo;s nature compared to Cloud Atlas: I was thinking about it in the last few days, and I was also a bit in doubt. My reasoning must have been that, since my protagonist is universally alone, others&rsquo; actions have no effect (quite literally because it&rsquo;s fair to think that there&rsquo;s nobody left); compared to Cloud Atlas, where people&rsquo;s actions have influences on other&rsquo;s stories, my story would be the opposite, hence why I used the term antithesis. But then I realized that if the protagonist is in this situation, then there must have been some kind of external influence. So, I should probably rephrase my statement like so: from now on, others&rsquo; influences are irrelevant to the protagonist&rsquo;s story; meaning that even if the protagonist searches themselves in their memories, none of them will help them remember their story.<br>
            Since it was clear to me that there won&rsquo;t be a resolution to this story, it&rsquo;s probable that everything will end up in a loop. Not a timeloop per se, more of a thoughts loop where at some point the protagonist realized that their method is not working, and they will start all over again. But maybe I can find other stratagems in the future.<br>
            The memories are the short stories that compose the entire project. They are told from the point of view of the protagonist of the story, but it&rsquo;s intended that they are being &ldquo;read&rdquo; or &ldquo;recollected&rdquo; by the person in the cell. I&rsquo;m thinking of ways to make this clear in every single text, maybe using recurrent elements or phrases at the beginning of each text. The stories are self-contained and they can be read in any order, but they are all part of a big story. Each text deals with the topic of isolation in a different way. I have some stories in mind, and I will make a list as soon as I can.<br>
            I hope I could answer your questions and delineate a bit more the direction of the project.<br>
            <br>
            01.03.2025<br>
            Logically speaking, how would the protagonist speak? Nobody will listen, so there is no need to use a neat language. I think it's more interesting to use a concise and aseptic language. I want to convey the same sense of systematicity of this introspective process in the language. Maybe every text should begin in the same way, introducing the characters using the same words. Maybe they should also end in the same way. Maybe this systematicity should slowly get lost as the protagonist loses their way in this process.<br>
            <br>
            05.03.2025<br>
            Reading Memorie di un viaggiatore spaziale was my next activity on the list, since judging from the premise I think it could really help me to structure the project. I decided to watch Cloud Atlas instead of reading it for brevity&rsquo;s sake (I wanted to start writing at least the premise to concretize it), but I may reconsider.<br>
            Regarding my statement on the project&rsquo;s nature compared to Cloud Atlas: I was thinking about it in the last few days, and I was also a bit in doubt. My reasoning must have been that, since my protagonist is universally alone, others&rsquo; actions have no effect (quite literally because it&rsquo;s fair to think that there&rsquo;s nobody left); compared to Cloud Atlas, where people&rsquo;s actions have influences on other&rsquo;s stories, my story would be the opposite, hence why I used the term antithesis. But then I realized that if the protagonist is in this situation, then there must have been some kind of external influence. So, I should probably rephrase my statement like so: from now on, others&rsquo; influences are irrelevant to the protagonist&rsquo;s story; meaning that even if the protagonist searches themselves in their memories, none of them will help them remember their story.<br>
            Since it was clear to me that there won&rsquo;t be a resolution to this story, it&rsquo;s probable that everything will end up in a loop. Not a timeloop per se, more of a thoughts loop where at some point the protagonist realized that their method is not working, and they will start all over again. But maybe I can find other stratagems in the future.<br>
            The memories are the short stories that compose the entire project. They are told from the point of view of the protagonist of the story, but it&rsquo;s intended that they are being &ldquo;read&rdquo; or &ldquo;recollected&rdquo; by the person in the cell. I&rsquo;m thinking of ways to make this clear in every single text, maybe using recurrent elements or phrases at the beginning of each text. The stories are self-contained and they can be read in any order, but they are all part of a big story. Each text deals with the topic of isolation in a different way. I have some stories in mind, and I will make a list as soon as I can.<br>
            I hope I could answer your questions and delineate a bit more the direction of the project!<br>
            17.03.2025<br>
            During the weekend I started reasoning (once again) on the point of the project. How should I explain it to others, especially considering the anticlimactic outcome (I&rsquo;m referring to the whole idea of the loop)?<br>
            The idea of absolute confinement is not new. I&rsquo;ve been building possible stories around this person stuck around a black hole for some time. I never really elaborate on any of my ideas around it, but the common topic was trying to define reality. Now, I have no idea of what reality really is, I certainly won&rsquo;t be the one to find out and it&rsquo;s not the point of the project anyway. But I like this contradiction: trying to define reality, in a situation where reality is unreliable.<br>
            I think this idea really set in after a brief discussion with Marc in the SPARK module. We were talking about Baudrillard and Simulacra and Simulation. At some point I said something like this: considering that we may have lost all reference to reality and that we live in a time where people feel extremely lonely, how can we identify ourselves without others and a solid reality?<br>
            I asked this question based on the words of Umberto Galimberti: identity is in essence other&rsquo;s recognition of ourselves. If you remove other&rsquo;s recognition, you&rsquo;ll probably search for your identity somewhere else. But if even this somewhere else is defective, your identity is defective. This is where we found ourselves today. And it&rsquo;s probably the reason why, unfortunately, identity is often instrumentalized.<br>
            So, I guess this is it: the point of the project is not finding out what reality is; the point is showing how reality is terribly complicated because we are terribly complicated. There is no resolution exactly because in the protagonist&rsquo;s situation there is no resolution. Something else should be done to escape this cycle. Something that, given the circumstances, the protagonist will never be able to do. But we are not trapped around a black hole, so we can.<br>
            In the case that I start feeling doubtful of the project, I must remember to read this text.<br>
            <br>
            31.03.2025<br>
            I was trying to delineate some elements for the story &ldquo;not enough senses&rdquo; to have a base to work on when I&rsquo;ll start writing it.<br>
            <br>
            The story takes inspiration from the game Outer Wilds, where a signal sent from the so called &ldquo;eye of the universe&rdquo; turns out to be older than the universe itself.<br>
            The premise is the same, with the difference that humanity is unable to completely study the astral object that is sending the signal. Now, I&rsquo;ve been trying to justify this inability.<br>
            <br>
            Of course, our perception of the universe is limited because of our senses. We are already unable to perceive &ldquo;simple&rdquo; things like sound or light that are out of our perceived frequency range, let alone a signal older than the universe. That&rsquo;s where technology comes into action.<br>
            <br>
            Somehow in this story even technology is not enough. But why? In the case of an antenna, for example, crucial aspects that influence its capabilities are size, design, materials, interferences and environmental factors. I think that the best way to go would be to exaggerate one of these elements to the point where it&rsquo;s clear that there is no possible solution to the problem.<br>
            <br>
            Next, I need to think about the catch of the text structure. How can I translate the concept of this story into a participatory mechanic? The concept of the story, more or less, is to explore the idea of &ldquo;universal solitude&rdquo; (I can&rsquo;t find a better way to call it), where the isolation is the awareness of not being able to completely understand the nature of the universe where we live. If we are not destined to understand it, then the universe was not designed for us.<br>
            <br>
            Maybe playing with user friendliness (making the page user unfriendly?).<br>
            <br>
            07.05.2025<br>
            I would now like to start writing the &ldquo;Not enough senses&rdquo; story with some of the ideas I&rsquo;ve previously gathered. Today I had this idea of telling the story from the perspective of a computer onboard the spaceship that&rsquo;s transporting the characters to the astronomical object emitting the signal. The story would be composed of short entries written by different characters, narrating the events and their thoughts as a journal. Plus, the computer itself would be a character that keeps functioning even after the death of all the humans onboard, although I don&rsquo;t want to make this computer sentient in any way; it&rsquo;s simply an agent of the story that keeps generating almost insignificant events by automatism.<br>
            <br>
            Since it&rsquo;s a computer, my idea to tell the story is not using text. Instead, I would like to use electrical signals. I think the best idea is to use sound. Each letter has a signal of a certain frequency, and the story is told using sound. A sort of &ldquo;sound alphabet&rdquo;. Although, I want the original text to be readable without the need to act too much on the page. Maybe I could use the sound as background noise, or the sound could activate with some basic user action like scrolling or pointing.<br>
            <br>
            Technically speaking it&rsquo;s not too hard to do. We are working now on a project in DIDES that involves sound on a webpage, so I&rsquo;m learning now how to deal with it.<br>
            <br>
            19.05.2025<br>
            Unfortunately, I must make a bit of a detour. We have to write a flash fiction for the SCIFI module due the 31st of May, should be around 3 / 4 pages long. I want to write mine in the same context of this project, but more focused on the actual protagonist rather than the single stories. I want to tell different aspects of the life of this isolated protagonist. But some of the ideas I have for this story don&rsquo;t align correctly with the concept of the project. I will nonetheless send you the text while I&rsquo;m writing it as a sort of addition that may or may not end up in the project once it&rsquo;s finished.<br>
            <br>
            24.05.2025<br>
            Yes, I took a look to Georges Perec a while ago and what really surprised me the most was his meticulousness in keeping those extradiegetic writing practices. For example the book without the &quot;et&quot; word, with the very fittingly title &quot;La Disparition&quot;. This way of playing with words to connect with the story is what I would like to achieve. In a way, I feel like it's the equivalent of the &quot;show don't tell&quot; principle in cinema. It reminds me of an Italian poet named Biagio Cepollaro who wrote an entire book of poetries using a very atypical indentation style. At the time I felt so fascinated by this stylistic choice that I got in touch with him by email and he explained to me the origin of this idea<br>
            <br>`
}