const textsIT = {
    "premise": {
        "title": "Premessa",
        "body": `La mia cella dista 71.52 anni luce dal pianeta Terra. Orbita attorno al buco nero RS 8513-928-8-5906646-198, attorno al quale sono stato mandato per motivazioni che non ricordo. Di me stesso conosco quanto segue: tutta la parte anteriore del mio corpo dal collo in gi&ugrave; e il retro delle mie gambe. 
                <br><br>Quando mi sento affamato mangio una razione di cibo. 
                <br>Quando mi sento assetato bevo una razione di acqua. 
                <br>Quando mi sento annoiato leggo uno dei libri presenti sullo scaffale della cella. 
                <br>Quando non sono affamato o assetato o annoiato, non faccio niente.<br>
                <br>Un pensiero mi turba. Non essendo pi&ugrave; a conoscenza delle sorti della specie umana, sarebbe irrealistico escludere di essere il solo umano rimasto in vita. Per qualche motivo, sento di dover ricordare il mio passato al fine di conservarlo per quanto pi&ugrave; tempo possibile. 
                <br><br>Da adesso in poi, quando non sono affamato o assetato o annoiato, cercher&ograve; di ricordare chi sono.<br>
`,
    },

    "conclusion": {
        "title": "Conclusione",
        "body": `C&rsquo;&egrave; qualcosa che non va.<br>
                <br>Temo di aver perso il filo. Possibile che siano queste le memorie che sto cercando?<br>
                <br>Ancora una volta, devo capire dove sto sbagliando.<br>
                `,
    },

    "rectangles": {
        "title": "Rettangoli",
        "body": `Spesso mi ritrovo a guardare lo stesso rettangolo verticale.<br>
                <br>Le proporzioni si avvicinano al rapporto di tre a cinque della sezione aurea. Lo spazio &egrave; suddiviso in quindici moduli rettangolari, con tre moduli lungo la dimensione orizzontale. I nove moduli superiori approssimano un quadrato, mentre il restante spazio &egrave; riservato al rettangolo principale. I rettangoli secondari, invece, sono allineati ad un terzo della lunghezza orizzontale del rettangolo principale.<br>
                <br>Sembra molto, ma ci si fa drammaticamente l&rsquo;abitudine.<br>
                <br>Quello che conta davvero &egrave; individuare la struttura della griglia, perch&eacute; da ci&ograve; ne deriva tutto il resto. Poi ci sono le proporzioni, senza le quali non si va da nessuna parte. Regola dei terzi, sezione aurea, margine, gerarchia visiva, contrasto dei colori; non fai caso a uno di questi dettagli e ti ritrovi dall&rsquo;altro capo del mondo.<br>
                <br>Quindi, parto da un rettangolo azzurro alto circa sei volte il mio corpo e passando per un piano verde che coprir&agrave; s&igrave; e no una decina di metri quadrati, finisco nelle lunge colonne e righe grige che ho imparato a percorrere a memoria. Ad una frequenza regolare un rettangolo bianco si avvicina e si ferma sempre nello stesso punto, aspetta che io ci salga sopra e riprende il suo cammino che, sia lodato il cielo, si pu&ograve; essere sicuri che non cambier&agrave; mai. Quando, dopo un&rsquo;incessante attesa condita di alti e fini rettangoli, comincio a vedere un agglomerato di rettangoli grigi particolarmente alti so che &egrave; il momento di abbandonare il rettangolo bianco. Di quei rettangoli grigi ne cerco unoc in particolare. Se &egrave; composto da due sezioni uguali alle estremit&agrave; connesse da una pi&ugrave; bassa di circa la met&agrave;, allora &egrave; l&igrave; che devo andare.<br>
                <br>Ora, avere a che fare con i rettangoli non &egrave; particolarmente complesso. Finch&eacute; stanno dove devono stare si ha tutto il tempo di identificarli. Ci sono per&ograve; altri rettangoli, quelli che si muovono come gli pare, diversi dal rettangolo bianco che mi accompagna dal blu al grigio. Questi hanno proporzioni completamente fuori dal comune. Ma ce ne sono talmente tanti che la loro sproporzionalit&agrave; &egrave; comune; soprattutto dove devo recarmi. Se la griglia &egrave; composta da 12 colonne e 7 righe, loro occupano 3 moduli sforando di tre quinti in alto, cinque noni a sinistra e se proprio gli gira male si sdraiano sui margini.<br>
                <br>Cerchi di passare da una pagina all&rsquo;altra e rischi di sbattere contro uno di questi abomini.<br>
                <br>Facciamo che io passo nel modulo destro pi&ugrave; vicino al mio. Ma no, ecco che il rettangolo semovente decide di cambiare modulo all&rsquo;ultimo e per poco non mi ritrovo con la faccia stirata. Ma la navigazione &egrave; l&rsquo;ultimo dei problemi.<br>
                <br>Su di una riga divisa in sette sezioni congruenti, ad una frequenza sufficientemente regolare, mi sento affamato. Non tutti i rettangoli possono essere mangiati, ma ove mi sto recando &egrave; zeppo di rettangoli commestibili. Quando un elemento si ripete a sufficienza e possibile riconoscerne il sapore a memoria. Qualora i rettangoli semoventi decidano che &egrave; il momento giusto di smorzare la ripetizione, cambiano i colori dei rettangoli commestibili &ndash; se si sentono particolarmente fantasiosi persino le proporzioni &ndash; nullificando completamente i miei sforzi mnemonici. Esattamente questo &egrave; ci&ograve; che &egrave; successo in questa sezione della riga.<br>
                <br>Inizio a vagare per la griglia alla ricerca di quei pochi rettangoli che non cambiano mai. Non sono particolarmente appassionato di questi rettangoli, ma almeno fino a quando non riprender&ograve; confidenza con le nuove composizioni, questi sono gli unici elementi certi a disposizione. La griglia &egrave; divisa in compartimenti di diverse misure. I compartimenti sono divisi per sapori, i sapori sono divisi in sotto-sapori. I sotto-sapori si distinguono dai colori. In genere prendo sempre tre dei rettangoli in proporzione nove a ventuno di colore verde. Sfortunatamente, di rettangoli in quella proporzione ce n&rsquo;&egrave; di pi&ugrave; colori. Alcuni di quei colori hanno sapori assolutamente insopportabili. Ovviamente, i colori di questi rettangoli sono cambiati completamente. Onde evitare di sprecare i miei preziosi rettangoli &egrave; cruciale capire quale dei nuovi colori &egrave; quello corretto.<br>
                <br>Li guardo a uno a uno da vicino e da lontano. Sono assolutamente identici, eccetto per il colore, appunto. Osservarli non mi aiuter&agrave; di certo. Provo a tastarli, annusarli e scuoterli. Tutti mi restituiscono la stessa consistenza, odore e rumore. Niente da fare. Mi guardo attorno, alla ricerca di un rettangolo semovente di colore azzurro. Quelli azzurri conoscono vita, morte e miracoli di ogni singolo rettangolo, di sicuro sapranno darmi la soluzione al mio problema.<br>
                <br>Ce n&rsquo;&egrave; uno a pochi moduli da me, intento a spostare alcuni rettangoli al loro posto. Prossimo dilemma: come diavolo faccio a fargli capire che sto cercando il rettangolo che prima era di colore verde? Mentre tento di escogitare un piano, il rettangolo semovente azzurro si gira verso di me e stride con vigore. Ancor prima di accorgermene &egrave; davanti a me. Devo averlo guardato troppo intensamente e avr&agrave; pensato che necessitassi di aiuto. Effettivamente &egrave; cos&igrave;, ma ora ho anche bisogno di aiuto per comunicare che ho bisogno di aiuto.<br>
                <br>Cerco di gesticolare la mia richiesta. Indico uno dei rettangoli che ho in mano, ci punto il dito e lo muovo su e gi&ugrave; qualche volta. Molto lentamente pronuncio &ldquo;questo!&rdquo;, nella speranza che il rettangolo azzurro capisca che mi sto riferendo al tipo di rettangolo che ho in mano. Poi, mi metto a disegnare in aria. <br>
                <br>Prima una foglia: un cerchio in basso, uno in alto dal diametro tre volte pi&ugrave; piccolo, tracciando una parabola ed inscrivendoci i cerchi. <br>
                <br>&ldquo;Verde!&rdquo;, di nuovo lentamente. Poi un albero: quattro triangoli isosceli uno sopra l&rsquo;altro, le cui lunghezze delle basi decrescono seguendo la successione di Fibonacci; 13, 8, 5 e 3. <br>
                <br>&ldquo;Verde!&rdquo;, ancora lentamente. Poi un trifoglio: tre triangoli equilateri nascenti da un punto centrale, pi&ugrave; una retta che sempre da quel punto scende.<br>
                <br>&ldquo;Ver-&rdquo;, vengo interrotto all&rsquo;improvviso. Il rettangolo azzurro si allunga leggermente e raggiunge un gruppo di rettangoli appena dietro di me. Me li poggia sulle mani che ancora stavano in aria a disegnare. Tre rettangoli in proporzione nove a ventuno di colore arancione. Rimango un attimo attonito. Possibile che siano questi quelli giusti? Ma come faceva a sapere che ne volevo tre?<br>
                <br>Tento di alzare lo sguardo per cercare chiss&agrave; quale risposta ai miei dubbi nel rettangolo semovente azzurro, ma prima di poterci arrivare mi sento afferrare il braccio. In qualche manciata di ripetizioni mi ritrovo in un modulo all&rsquo;altro, difronte a gruppi di rettangoli che riconosco. Sono i rettangoli che prendo solitamente, semplicemente hanno cambiato colore. Ogni volta che ci fermiamo, il rettangolo semovente azzurro mi porge la giusta tipologia e quantit&agrave; di rettangoli, per poi riafferrarmi e portarmi nel prossimo modulo. Poche ripetizioni dopo, il rettangolo semovente azzurro stride nuovamente con vigore, e torna nel modulo nel quale stava sistemando i rettangoli precedentemente.<br>
                <br>Rimango fisso nella posizione in cui mi sono ritrovato per un numero di ripetizioni che non sono in grado di contare. Mi ritrovo ora avendo in mano tutto ci&ograve; che mi serve per la prossima riga di sette sezioni congruenti, senza aver capito come sia successo.<br>
                <br>Mentre aspetto pazientemente che il rettangolo bianco mi riporti da dove sono venuto, rifletto su quanto accaduto. Possibile che quel rettangolo semovente abbia memorizzato i rettangoli che prendo solitamente? Non so se esserne grato o inquietato. Sta di fatto che senza il suo aiuto ci avrei messo molte pi&ugrave; ripetizioni, probabilmente anche sbagliando.<br>
                <br>Devo sdebitarmi. In qualche modo.<br>
                <br>Il tragitto inverso sul rettangolo bianco pare stranamente meno sofferente. Sono impaziente, per qualche motivo; al punto che l&rsquo;attesa viene anestetizzata. Guardo i rettangoli commestibili che mi sono portato dietro e penso che, se anche dovessero essere sbagliati, non mi causerebbe alcun fastidio; se anche dovessero essere disgustosi, li mangerei lo stesso. Comincio a intravvedere le lunge colonne e righe grige connesse al mio rettangolo azzurro alto circa sei volte il mio corpo. Quando mi ci trovo davanti, ci entro.<br>
                <br>Le solite scale, che mi portano al solito uscio, che mi portano nel corridoio di casa. Lascio tutto l&igrave;, ora proprio non posso perdere tempo. Entro in camera mia, e subito mi rivolgo verso la libreria. Tra i tanti libri che non sono riuscito a non portarmi dietro, ci sta anche un rettangolo rosso alto e fine. Non ricordo da dove sia saltato fuori, ma fino a d&rsquo;ora l&rsquo;ho sempre ignorato a causa della sua grande difficolt&agrave;. Allora lo tiro fuori. Pesa parecchio. Lo poggio sulla scrivania e comincio a guardarci dentro talmente intensamente da ritrovarmici con la testa infilata dentro. Non so quanto tempo passa, ma so che ora sento la testa pesante. Questo &egrave; davvero il rettangolo pi&ugrave; difficile che io abbia mai visto. Per&ograve;, ho l&rsquo;impressione che sbatterci contro sia servito a qualcosa. Difatti, ho una realizzazione. Di colpo mi alzo dalla sedia, voglio provare una cosa.<br>
                vEsco dal rettangolo azzurro in tutta fretta. Ripercorro per l&rsquo;ennesima volta le lunghe colonne e righe grige fin dove il rettangolo bianco si ferma. Ma questa volta non ci salgo. Quando il rettangolo bianco riparte, quel rettangolo verticale che spesso mi ritrovo a guardare si rivela: proporzioni di tre a cinque rispetto alla sezione aurea, spazio suddiviso in quindici moduli regolari&#8230; Insomma, ci siamo capiti. Questa volta lo guardo attentamente. Poi penso al rettangolo rosso nella mia libreria. Di nuovo guardo il rettangolo. Di nuovo penso al rettangolo rosso.<br>
                <br>Ah, ecco! Ora capisco!<br>
                `
    },

    "jailer": {
        "title": "Al mio carceriere",
        "body": `Al mio carceriere.<br>
                <br>Al tramonto dell&rsquo;universo, ove le ultime stelle soffrono la morte del loro idrogeno tingendosi di rosso e le ultime civilt&agrave; rincorrono il loro moribondo calore, una presenza al limitare del nulla, che pi&ugrave; nulla non esiste, in un lieve momento di lucidit&agrave;, trova il modo di arrestare la sua morbosa ricerca di qualcosa, che pi&ugrave; qualcosa non esiste, per dedicare i suoi pensieri a colui che lo ha concepito.<br>
                <br>Quella presenza sono io.<br>
                <br>Le pareti della mia cella non riflettono alcunch&eacute;, di certo non la mia immagine. Per quel che ne so, la mia testa potrebbe essere composta da una qualche materia incolore, insapore, inodore, inudibile, impalpabile. Il resto del corpo lo vedo quando abbasso il volto, quando alzo le braccia, quando giro le gambe. Il resto rimane dimenticato.<br>
                <br>Dimenticato perch&eacute; il mio carceriere si &egrave; assicurato che cos&igrave; fosse. Ma non fraintendere: non parlo di coloro che mi hanno vincolato a ci&ograve; che pi&ugrave; c&rsquo;&egrave; di irraggiungibile nell&rsquo;universo. Parlo di chi lo ha reso possibile.<br>
                <br>Parlo di te.<br>
                <br>Vorrei poter dire che questo discorso non ha alcun risvolto spirituale, ma l&rsquo;assurdit&agrave; di parlare a qualcuno che non ha modo alcuno di esistere qui e ora rende il mio discorso valido quanto una preghiera. Ad ogni modo, non ho mezzo di sapere se quel qualcuno che prima dell&rsquo;odierno me &egrave; esistito fosse o meno un qualche monaco solito a decantare ai piedi di un qualche altare.<br>
                <br>In una situazione molto diversa dalla mia, immagino che dovrei sentirmi furioso o disperato. Il problema &egrave; qui dentro il tener conto di quel che succede non ha particolare senso. Pu&ograve; darsi che io mi sia sentito furioso per mesi, disperato per anni, ma se cos&igrave; fosse, queste emozioni sarebbero state sostituite dal restante nulla che maggiormente ricopre il tempo qui. Se di tempo ancora si pu&ograve; parlare. Un qualsiasi evento qui, insignificante o gargantuesco che sia, non conta molto rispetto al vuoto che lo susseguir&agrave;. Nulla di quello che mi &egrave; possibile fare o essere ha un senso. Non lo aveva neppure prima, quando gli esseri umani vivevano in quel granello di sabbia chiamato Terra nel mezzo dell&rsquo;oceano dell&rsquo;universo. Ma quantomeno quell&rsquo;immensit&agrave; poteva essere concettualizzata, in un certo senso fronteggiata.<br>
                <br>Certamente lasciarmi in questo posto per l&rsquo;eternit&agrave; non deve essere una prospettiva particolarmente interessante. Perci&ograve;, hai deciso di giocare con la mia umanit&agrave;. Alla realizzazione dell&rsquo;inevitabile estinzione della specie umana, un irresistibile istinto di conservazione mi obbliga a lunghi viaggi in ricordi che non mi appartengono, che forse non sono neppure autentici, alla ricerca di un&rsquo;identit&agrave;, di un motivo, di una storia. Di nuovo, quella che potrebbe sembrare un&rsquo;anomalia, questa realizzazione, non ha alcuna valenza. Potrebbe essere successa un istante fa, o potrebbe succedere tra svariati secoli. Ad ogni modo, da qualche parte esiste. Ma tu non sei particolarmente romantico, i lieto fine non ti piacciono. Non sono destinato a ricordare niente di utile. La mia fame di informazioni non sar&agrave; mai soddisfatta. I concetti si mischiano, si ricreano e si riscrivono, perch&eacute; nel bel mezzo del nulla al cervello non basta niente. Il dramma di questa storia per&ograve;, &egrave; che a me non importa. Questi tentativi deliranti non mi provocano alcunch&eacute;. Come ho detto, non avrebbe senso in ogni caso.<br>
                <br>La verit&agrave; &egrave; che questa esperienza non mi appartiene. Se dovesse essere utile, allora lo sarebbe altrove. Qualche posto dove il tempo ancora esiste. Dove ancora infuriarsi provoca la rottura di oggetti. Dove ancora disperarsi ti fa sentire la pacia pesante. Dove ancora isolarsi significa confondere ci&ograve; che ancora esiste con quello che non esiste pi&ugrave;.<br>
                <br>Immagino che il mio scopo sia questo. <br>
                `,
    },

    "klein": {
        "title": "Infilare un gatto in una bottiglia di Klein",
        "body": `La mia cella dista 71.52 anni luce dal pianeta Terra. Orbita attorno al buco nero RS 8513-928-8-5906646-198, attorno al quale sono stato mandato per motivazioni che non ricordo. Di me stesso conosco quanto segue: tutta la parte anteriore del mio corpo dal collo in gi&ugrave; e il retro delle mie gambe. Quando mi sento affamato mangio una razione di cibo. Quando mi sento assetato bevo una razione di acqua. Quando mi sento annoiato leggo uno dei libri presenti sullo scaffale della cella. Quando non sono affamato o assetato o annoiato, non faccio niente.<br>
                <br>Questa &egrave; la mia condanna: un cubo di 27 metri cubici in titanio alimentato da un generatore termoelettrico a radioisotopi, il quale si occupa anche di mantenere la temperatura dell&rsquo;ambiente costantemente a 18 gradi centigradi; razioni di cibo ad alto contenuto calorico sono stimate per durare svariati decenni, l&rsquo;acqua viene purificata e riciclata. Una lampada Led appesa al soffitto illumina la stanza, proprio sotto alla lampada c&rsquo;&egrave; un portello. Se dovessi decidere di porre fine alla mia condanna, allora dovrei spalancarlo e lasciare che il vuoto dello spazio riempi la cella. Infine, il cubo &egrave; confinato attorno a quel corpo celeste dal quale bisogna sempre stare alla larga. Tentare di raggiungermi sarebbe una missione troppo pericolosa anche per il pi&ugrave; spericolato degli esploratori.<br>
                <br>Fortunatamente non sono da solo qui dentro. I miei coinquilini si nascondono nei libri. Ci sono tante piccole personcine che li abitano. A dire il vero sono sempre gli stessi, ma in diversi libri hanno diverse facce. Per esempio, nel libro blu sono tutti schizzinosi e se ne stanno ognuno nel proprio spazio. In quello arancione ci si diverte sempre e tutti sorridono. In quello giallo hanno tutti malinconia di casa e sono un po&rsquo; tristi. In quello verde tutti ballano facendo piroette e salti da tutte le parti. Quello rosso non si apre mai, per nessun motivo. I coinquilini si arrabbiano subito.<br>
                <br>Il Gatto Loquace si sdraia sempre a fianco del materasso. &Egrave; arrivato e poi non se n&rsquo;&egrave; pi&ugrave; andato. A volte il Gatto Loquace si sente affamato, perci&ograve; gli do una parte di razione di cibo. A volte il Gatto Loquace si sente assetato, perci&ograve; gli do una parte di razione di acqua. A volte il Gatto Loquace si sente annoiato, perci&ograve; parla. Quando il Gatto Loquace non si sente affamato o assetato o annoiato, non fa niente.<br>
                <br>&laquo;Gatto Loquace, quando sei arrivato?&raquo;<br>
                <br>&laquo;Ieri. Oggi. Domani. Che differenza fa?&raquo;<br>
                <br>Il Gatto Loquace ha ragione. Di queste differenze non me ne faccio niente. Stando nel nulla tutto quello che succede perde di importanza. Nemmeno il &ldquo;quando&rdquo; ha un significato. Se spuntassero racconti dalla mia testa, questi potrebbero essere successi migliaia di anni fa, oppure poche ore fa, oppure stanno succedendo ora, oppure ancora devono succedere.<br>
                <br>Ora sto fermo. Ora cammino. Se sento le gambe svanire cammino. Se sento le gambe cedere mi fermo. Bisogna fare sempre molta attenzione a non calpestare il portello. Chiss&agrave; che potrebbe cedere all&rsquo;improvviso. Perci&ograve; finisco sempre per girarci intorno. A volte il Gatto Loquace si aggiunge alla passeggiata. Mi passa tra le gambe o mi sta dietro. Il Gatto Loquace invece sul portello ci passa. Ma il Gatto Loquace &egrave; leggero, perci&ograve; il portello lo accarezza appena.<br>
                <br>&laquo;Gatto Loquace, ti va di leggere un libro?&raquo;<br>
                <br>Allora sfilo il libro blu dallo scaffale e faccio uscire i coinquilini.<br>
                <br>&laquo;Gatto Loquace, vedi? Che precisini che sono questi personaggi!&raquo;<br>
                <br>&laquo;Non &egrave; cos&igrave; che si legge un libro&raquo;<br>
                <br>Il Gatto Loquace spiega che non basta fissare le pagine per tirare fuori i personaggi. Devo obbligare le personcine a stare vicine e in fila una dietro l&rsquo;altra. Mi sforzo e mi sforzo ancora. I coinquilini non ci sono pi&ugrave;.<br>
                <br>&ldquo;Le funzioni anonime sono una forma di funzione nidificata, che consente l'accesso alle variabili nella portata della funzione contenitrice (variabili non locali). Bench&eacute; siano nominate come funzioni annidate, non possono essere ricorsive senza l'aiuto di un operatore fixed-point combinator (funzione di ordine superiore) che in questo caso viene chiamato fixpoint anonimo o ricorsione anonima.&rdquo;<br>
                <br>&laquo;Gatto Loquace, tutti i libri sono cos&igrave;?&raquo;<br>
                <br>Prendo il libro verde.<br>
                <br>&ldquo;Chi &egrave; costui che oscura il consiglio con parole insipienti? Cingiti i fianchi come un prode, io t'interrogher&ograve; e tu mi istruirai. Dov'eri tu quand'io ponevo le fondamenta della terra? Dillo, se hai tanta intelligenza! Chi ha fissato le sue dimensioni, se lo sai, o chi ha teso su di essa la misura?&rdquo;<br>
                <br>Perdere i coinquilini mi ha fatto venire fame. La razione di cibo si strappa e si sfila, cos&igrave; rimane un piccolo parallelepipedo beige duro e fragile. Il Gatto Loquace mi guarda intensamente. Anche il Gatto Loquace vuole mangiare. La razione si spezza facilmente, cadono delle briciole sul pavimento e il Gatto Loquace ci si fionda. Lascio a terra anche un piccolo pezzo di razione, che il Gatto Loquace divora. Finisco la razione mentre guardo il Gatto Loquace masticare la sua parte. Mi rimane il gusto di gomitolo di lana.<br>
                <br>Il Gatto Loquace se ne va. Cos&igrave; dice.<br>
                <br>&laquo;Gatto Loquace, dove devi andare?&raquo;<br>
                <br>&laquo;Vado ad assistere alla fine dell&rsquo;universo. Se ancora ce ne sono, gli ultimi esseri viventi si sono rifugiati attorno alle ultime giganti rosse. Ma anche queste termineranno il loro idrogeno ponendo fine all&rsquo;esistenza dell&rsquo;entropia&raquo;<br>
                <br>&laquo;Gatto Loquace, come pu&ograve; essere vero tutto questo?&raquo;<br>
                <br>&laquo;Non lo sai? Attorno al buco nero il tempo &egrave; stagnato per via della relativit&agrave;. Ma fuori si va avanti lo stesso. Non c&rsquo;&egrave; nessun altro nell&rsquo;universo che si trovi nella tua condizione. La tua condanna inizia ora&raquo;<br>
                <br>&laquo;Gatto Loquace, per favore non andartene&raquo;<br>
                <br>Il Gatto Loquace non c&rsquo;&egrave; pi&ugrave;.<br>
                <br>Il libro rosso non si arrabbia pi&ugrave;. Spero che si infuri ogni volta che lo apro, ma non sembra pi&ugrave; averne voglia. Qualcuno dovr&agrave; pur farmi sentire male. Qualcuno dovr&agrave; pur rinfacciare i miei reati. Solo il peggiore dei criminali potrebbe meritarsi questa condanna. Allora arrabbiati libro rosso! Dimmi che ho sbagliato, dimmi che non sono degno di vivere! Urlami contro come ti sto urlando contro io! Ricordami quali inimmaginabili sofferenze ho causato a color che avevo intorno! Rinfacciami che coloro che mi hanno rinchiuso fuori dal tempo avevano ragione! Perch&eacute;, se cos&igrave; non fosse, se davvero non c&rsquo;&egrave; motivo, se &egrave; tutto per caso, allora io non posso avere pace. <br>
                <br>Il libro rosso rimane in silenzio. &Egrave; il portello a parlare. Qualcuno bussa. Forse qualcuno &egrave; scampato al destino dell&rsquo;universo. Forse il Gatto Loquace ha cambiato idea. Forse qualche altro detenuto ha trovato il modo di fuggire. Ma chi mai potr&agrave; bussare qui dove non rimane nulla? Temo che fuori non ci sia nessuno. Temo che ha bussare sia io. Temo che rispondere a questo richiamo sia un grave errore.<br>
                <br>La lampada Led ha smesso di investire la stanza con la sua luce. I libri danzano nella stanza tra le briciole delle razioni. Senza neppure accorgermene, sono in un bicchiere di Klein.<br>
                `

        }
}