const textsEN = {
    "premise": {
        "title": "Premise",
        "body": `My cell is 71.52 light-years away from planet Earth. It orbits around the black hole RS 8513-928-8-5906646-198, where I was sent for reasons I no longer remember. This is what I know about myself: the entire front of my body from the neck down, and the back of my legs.<br>
                <br>When I feel hungry, I eat a ration of food.<br>
                When I feel thirsty, I drink a ration of water.<br>
                When I feel bored, I read one of the books on the shelf in my cell.<br>
                When I am neither hungry nor thirsty nor bored, I do nothing.<br>
                <br>A thought unsettles me. Since I no longer know the fate of the human species, it would be unrealistic to rule out the possibility that I am the last human alive. For some reason, I feel the need to remember my past in order to preserve it for as long as possible.<br>
                <br>From now on, when I am neither hungry nor thirsty nor bored, I will try to remember who I am.<br>`,
    },

    "conclusion": {
        "title": "Conclusion",
        "body": `Something&rsquo;s not right. <br>
                I&rsquo;m afraid I&rsquo;ve lost the thread. Is it possible that these are the memories I&rsquo;ve been looking for? <br>
                Once again, I need to figure out where I&rsquo;m going wrong.<br>`,
    },

    "rectangles": {
        "title": "Rectangles",
        "body": `I often find myself staring at the same vertical rectangle. <br>
                Its proportions are close to the three to five ratio of the golden mean. The space is divided into fifteen rectangular modules, with three spanning the horizontal dimension. The top nine modules approximate a square, while the remaining space is reserved for the main rectangle. The secondary rectangles, on the other hand, align with one-third of the horizontal length of the main rectangle. <br>
                It seems like a lot, but you get used to it, dramatically so. <br>
                <br>What truly matters is identifying the grid structure, because everything else follows from that. Then there are the proportions, without them you&rsquo;re lost. Rule of thirds, golden section, margin, visual hierarchy, color contrast; ignore even one of these details, and you&rsquo;ll find yourself on the other side of the world. <br>
                <br>So, I start from a blue rectangle about six times my height, and passing through a green plane that barely covers ten square meters, I end up in the long gray columns and rows I have learned to navigate by heart. At regular intervals, a white rectangle approaches and stops at the same point every time, waiting for me to step inside before resuming its journey, a journey that, thank heavens, will never change. After an endless wait punctuated by tall, thin rectangles, when I begin to see a cluster of particularly high gray rectangles, I know it&rsquo;s time to leave the white rectangle. Among those gray rectangles, I search for one in particular. If it consists of two identical sections at the ends, connected by a lower one about half their height, then that&rsquo;s where I need to go.<br>
                <br>Now, dealing with rectangles is not particularly complicated. As long as they stay where they&rsquo;re supposed to be, there&rsquo;s plenty of time to identify them. But there are other rectangles, ones that move as they please, different from the white rectangle that accompanies me from blue to grey. These have proportions that are completely out of the ordinary. But there are so many of them that their disproportionality becomes common, especially where I need to go. If the grid is made up of 12 columns and 7 rows, they occupy 3 modules, sticking out by three-fifths at the top, five ninths to the left, and if things go really badly, they stretch out over the edges. <br>
                <br>You try to move from one page to another and risk bumping into one of these abominations. <br>
                <br>Let&rsquo;s say I try to pass through the module closest to me on the right. But no, there goes the self moving rectangle, switching modules at the last second, and I almost end up with my face stretched out. But navigation is the least of the problems.<br>
                <br>On a line divided into seven congruent sections, at a sufficiently regular frequency, I start feeling hungry. Not all rectangles are edible, but where I&rsquo;m headed is full of edible rectangles. When an element repeats enough times, you can recognize its taste by memory. However, if the moving rectangles decide it&rsquo;s time to break the pattern, they change the colors of the edible rectangles, sometimes even their proportions, completely nullifying my memorization efforts. This is exactly what has happened in this section of the line. <br>
                <br>I begin wandering through the grid in search of the few rectangles that never change. I&rsquo;m not particularly fond of these rectangles, but until I regain familiarity with the new compositions, they are the only certain elements available. The grid is divided into compartments of different sizes. The compartments are divided by flavors, and the flavors are divided into sub-flavors. The sub flavors are distinguished by colors. I usually take a couple of rectangles with a 9:21 proportion in green. Unfortunately, there are multiple rectangles in that proportion, but in different colors. Some of those colors have absolutely unbearable flavors. Naturally, the colors of these rectangles have completely changed. To avoid wasting my precious rectangles, it&rsquo;s crucial to determine which of the new colors is the correct one. <br>
                <br>I look at them one by one, both up close and from a distance. They are absolutely identical, except for their color. Observing them won&rsquo;t help. I try touching them, smelling them, and shaking them. They all give me the same texture, scent, and sound. Nothing. I glance around, looking for a moving rectangle in light blue. The light blue ones know the life, death, and miracles of every single rectangle; surely, they will have the solution to my problem. <br>
                <br>There&rsquo;s one just a few modules away from me, busy placing some rectangles in their spots. Next dilemma: how on earth do I make it understand that I&rsquo;m looking for the rectangle that used to be green? As I try to devise a plan, the light blue moving rectangle turns toward me and screeches loudly. Before I even realize it, it&rsquo;s right in front of me. I must have stared at it too intensely, and it must have thought I needed help. Which is true, but now I also need help communicating that I need help. <br>
                <br>I try to gesture my request. I point to one of the rectangles in my hand, direct my finger at it, and move it up and down a few times. Very slowly, I say &ldquo;this!&rdquo; hoping the blue rectangle understands that I&rsquo;m referring to the type of rectangle I&rsquo;m holding. Then, I start drawing in the air. <br>
                <br>First, a leaf: a large circle at the bottom, a much smaller one above it, three times smaller in diameter, then tracing a parabola and inscribing the circles. &ldquo;Green!&rdquo; I say again, slowly. Then a tree: four isosceles triangles stacked one above the other, with base lengths decreasing according to the Fibonacci sequence: 13, 8, 5, and 3. <br>
                <br>&ldquo;Green!&rdquo; again slowly. Then a clover: three equilateral triangles radiating from a central point, plus a line descending from the same point. <br>
                <br>&ldquo;Gre&#8230;&rdquo; I&rsquo;m suddenly interrupted. The blue rectangle stretches slightly and reaches for a group of rectangles just behind me. It places them in my still raised hands. Three orange rectangles in a 9:21 ratio. I stand there stunned. Could these really be the right ones? But how did it know I needed three? <br>
                <br>I try to look up, searching for some sort of answer in the moving blue rectangle, but before I can, I feel my arm being grabbed. After a few cycles, I find myself in another module, in front of groups of rectangles I recognize. They&rsquo;re the rectangles I usually take, just in different colors. Each time we stop, the moving blue rectangle hands me the right type and amount of rectangles, then grabs me again and moves me to the next module. A few cycles later, the moving blue rectangle chirps loudly once more and returns to the module where it had been sorting rectangles earlier. <br>
                <br>I remain frozen in place for a number of cycles I can&rsquo;t count. I now find myself holding everything I need for the next row of seven congruent sections, without understanding how it all happened. <br>
                <br>While I patiently wait for the white rectangle to take me back to where I came from, I reflect on what happened. Is it possible that the moving rectangle memorized the ones I usually take? I&rsquo;m not sure whether to feel grateful or creeped out. The fact is, without its help, it would&rsquo;ve taken me many more cycles, probably making mistakes too. <br>
                <br>I need to repay the favor. Somehow, I don&rsquo;t know how, but I must. <br>
                <br>The reverse journey on the white rectangle seems strangely less painful. I&rsquo;m impatient, for some reason; so much so that the waiting feels numbed. I look at the edible rectangles I brought with me and think that, even if they turn out to be the wrong ones, it wouldn&rsquo;t bother me; even if they&rsquo;re disgusting, I&rsquo;d eat them anyway. I start to glimpse the long gray columns and rows connected to my blue rectangle, which is about six times taller than I am. When I get in front of it, I go inside. <br>
                <br>The usual stairs, leading to the usual door, leading to the hallway at home. I leave everything there; right now, I simply don&rsquo;t have time to waste. I go into my room and immediately turn to the bookshelf. Among the many books I couldn&rsquo;t stop myself from bringing, there&rsquo;s also a tall, thin red rectangle. I don&rsquo;t remember where it came from, but until now I&rsquo;ve always ignored it because of how difficult it is. So, I pull it out. It&rsquo;s quite heavy. I place it on the desk and start looking inside it so intensely that I end up with my head stuck in it. I don&rsquo;t know how much time passes, but I know my head feels heavy now. This is truly the most difficult rectangle I&rsquo;ve ever seen. But somehow, I get the feeling that banging my head against it has helped. In fact, I&rsquo;ve had a realization. Suddenly, I jump up from the chair, I want to try something. <br>
                <br>I rush out of the blue rectangle. Once again, I walk the long gray columns and rows to where the white rectangle ends. But this time, I don&rsquo;t get on it. When the white rectangle starts moving again, that vertical rectangle I often find myself staring at reveals itself: proportions of three to five according to the golden ratio, space divided into fifteen regular modules... You get the idea. This time, I look at it closely. Then I think about the red rectangle on my bookshelf. I look at the rectangle again. I think about the red rectangle again. <br>
                <br>Ah, I get it now!<br>`
    },

    "jailer": {
        "title": "To my jailer",
        "body": `At the sunset of the universe, where the last stars suffer the death of their hydrogen by turning red and the last civilizations chase their dying warmth, a presence at the edge of nothingness&mdash;where nothing no longer exists&mdash;finds, in a brief moment of clarity, a way to halt its morbid search for something&mdash;of which there is no longer anything&mdash;to devote its thoughts to the one who conceived it.<br>
                <br>
                That presence is me.<br>
                <br>The walls of my cell reflect nothing&mdash;certainly not my image. For all I know, my head could be made of some colorless, tasteless, odorless, soundless, intangible substance. I see the rest of my body when I lower my gaze, when I raise my arms, when I turn my legs. The rest remains forgotten.<br>
                <br>Forgotten because my jailer made sure it would be so. But don&rsquo;t misunderstand me: I&rsquo;m not talking about those who bound me to what is most unreachable in the universe. I&rsquo;m talking about the one who made it possible.<br>
                <br>I&rsquo;m talking about you.<br>
                <br>I wish I could say this speech has no spiritual connotation, but the absurdity of speaking to someone who has no way of existing here and now makes this as valid as a prayer. Anyway, I have no way of knowing whether the one who existed before the current me was some monk used to chanting at the foot of some altar or not.<br>
                <br>In a very different situation, I imagine I would feel furious or desperate. The problem is that, in here, keeping track of what happens makes little sense. Maybe I was furious for months, desperate for years&mdash;but even if so, those emotions would have been replaced by the rest of the nothingness that makes up most of the time here. If time is even still a thing. Any event here, insignificant or gargantuan, doesn&rsquo;t amount to much compared to the void that will follow it. Nothing I can do or be has any meaning. It didn&rsquo;t even have meaning before, when humans lived on that grain of sand called Earth in the middle of the universe&rsquo;s ocean. But at least that vastness could be conceptualized&mdash;somehow, faced.<br>
                <br>Certainly, leaving me here for eternity isn&rsquo;t exactly an exciting prospect. So, you decided to play with my humanity. With the realization of the inevitable extinction of the human species, an irresistible survival instinct forces me on long journeys through memories that aren&rsquo;t mine&mdash;maybe not even real&mdash;searching for an identity, a reason, a story. Again, what might seem like an anomaly&mdash;this realization&mdash;has no value. It could have happened a moment ago, or centuries from now. Regardless, it exists somewhere. But you aren&rsquo;t particularly romantic. Happy endings don&rsquo;t suit you. I am not meant to remember anything useful. My hunger for information will never be satisfied. Concepts blur, recreate, and rewrite themselves&mdash;because in the middle of nothingness, the brain cannot settle for nothing.<br>
                <br>The tragedy of this story, however, is that I don&rsquo;t care. These delirious attempts provoke nothing in me. As I said, it wouldn&rsquo;t make sense anyway.<br>
                <br>The truth is, this experience doesn&rsquo;t belong to me. If it&rsquo;s meant to be useful, then it would be so elsewhere. Somewhere time still exists. Where getting angry still means breaking things. Where despair still makes your stomach heavy. Where isolating yourself still means confusing what still exists with what no longer does.<br>
                <br>I suppose that is my purpose.<br>`,
    },

    "klein": {
        "title": "Fitting a cat in a Klein bottle",
        "body": `My cell is 71.52 light years away from planet Earth. It orbits the black hole RS 8513-928-8-5906646-198, around which I was sent for reasons I no longer remember. Of myself, I know the following: the entire front of my body from the neck down, and the backs of my legs. When I feel hungry, I eat a food ration. When I feel thirsty, I drink a water ration. When I feel bored, I read one of the books on the cell's shelf. When I am not hungry or thirsty or bored, I do nothing.<br>
                <br>This is my sentence: a 27-cubic-meter titanium cube powered by a radioisotope thermoelectric generator, which also keeps the environment at a constant temperature of 18 degrees Celsius; high-calorie food rations are estimated to last several decades, and the water is purified and recycled. A LED lamp hangs from the ceiling and lights up the room. Right beneath the lamp is a hatch. If I ever decided to end my sentence, I would have to open it wide and let the vacuum of space fill the cell. Finally, the cube is locked in orbit around that celestial body one must always avoid. Trying to reach me would be too dangerous, even for the most reckless of explorers.<br>
                <br>Fortunately, I&rsquo;m not alone here. My roommates hide inside the books. There are many tiny little people living in them. Truth be told, they&rsquo;re always the same ones, but in different books they wear different faces. For example, in the blue book they&rsquo;re all fussy and keep to their own space. In the orange one, they&rsquo;re always having fun and everyone is smiling. In the yellow one, they&rsquo;re all homesick and a bit sad. In the green one, they&rsquo;re all dancing, twirling and leaping all over the place. The red one never opens. Under no circumstances. The roommates get angry immediately. <br>
                <br>The Loquacious Cat always lies beside the mattress. It came and never left again. Sometimes the Loquacious Cat feels hungry, so I give it part of my food ration. Sometimes the Loquacious Cat feels thirsty, so I give it part of my water ration. Sometimes the Loquacious Cat feels bored, so it talks. When the Loquacious Cat isn&rsquo;t hungry, or thirsty, or bored, it does nothing. <br>
                <br>&laquo;Loquacious Cat, when did you arrive?&raquo;<br>
                <br>&laquo;Yesterday. Today. Tomorrow. What difference does it make?&raquo;<br>
                <br>The Loquacious Cat is right. These differences mean nothing to me. In the middle of nothingness, everything that happens loses its meaning. Not even &ldquo;when&rdquo; matters anymore. If stories sprout from my head, they might have happened thousands of years ago, or just a few hours ago, or they&rsquo;re happening now, or they haven&rsquo;t happened yet.<br>
                <br>Now I stand still. Now I walk. If I feel my legs vanish, I walk. If I feel my legs give out, I stop. You must always be very careful not to step on the hatch. Who knows, it might suddenly give way. So I always end up circling around it. Sometimes the Loquacious Cat joins me on the walk. It waves between my legs or follows behind me. The Loquacious Cat, however, walks right over the hatch. But the Loquacious Cat is light, so it&rsquo;s as if the hatch just gently strokes it. <br>
                <br>&laquo;Loquacious Cat, would you like to read a book?&raquo;<br>
                <br>I slide the blue book off the shelf and let the roommates out. <br>
                <br>&laquo;Loquacious Cat, see? How fussy these characters are!&raquo;<br>
                <br>&laquo;That&rsquo;s not how you read a book&raquo;<br>
                <br>The Loquacious Cat explains that it&rsquo;s not enough to stare at the pages to bring the characters out. I have to force the little people to stay close together and line up one after the other. I try and I try again. The roommates are gone. <br>
                <br>&ldquo;Anonymous functions are a form of nested function, allowing access to the variables within the scope of the containing function (non-local variables). Though they are named like nested functions, they cannot be recursive without the aid of a fixed-point combinator (a higher-order function), which in this case is referred to as an anonymous fixpoint or anonymous recursion.&rdquo; <br>
                <br>&laquo;Loquacious Cat, are all books like this?&raquo;<br>
                <br>I pick up the green book. <br>
                <br>&ldquo;Who is this that obscures my plans with words without knowledge? Brace yourself like a man; I will question you, and you shall answer me. Where were you when I laid the earth&rsquo;s foundation? Tell me, if you understand. Who marked off its dimensions? Surely you know! Who stretched a measuring line across it?&rdquo;<br>
                <br>Losing my roommates made me hungry. The food ration tears open and slides out, leaving a small beige parallelepiped&mdash;hard and brittle. The Loquacious Cat stares at me intensely. The Loquacious Cat wants to eat too. The ration breaks easily; crumbs fall to the floor and the Loquacious Cat pounces on them. I leave a small piece on the ground, which the Loquacious Cat devours. I finish my portion while watching the Loquacious Cat chew his. I&rsquo;m left with the taste of a ball of yarn. <br>
                <br>The Loquacious Cat leaves. Or so he says. <br>
                <br>&laquo;Loquacious Cat, where are you going?&raquo;<br>
                <br>&laquo;I&rsquo;m going to witness the end of the universe. If any remain, the last living beings have taken refuge around the final red giants. But even those will run out of hydrogen, putting an end to entropy itself&raquo;<br>
                <br>&laquo;Loquacious Cat, how can any of this be true?&raquo;<br>
                <br>&laquo;Don&rsquo;t you know? Around the black hole, time stagnates because of relativity. But outside, everything keeps going. There&rsquo;s no one else in the universe who finds themselves in your condition. Your sentence begins now&raquo;<br>
                <br>&laquo;Loquacious Cat, please don&rsquo;t go&raquo;<br>
                <br>The Loquacious Cat is no longer here. The red book doesn&rsquo;t get angry anymore. I hope it lashes out every time I open it, but it doesn&rsquo;t seem to want to anymore. Someone has to make me feel bad. Someone has to hold my crimes against me. Only the worst kind of criminal could deserve this sentence. Get angry, red book! Tell me I was wrong; tell me I&rsquo;m not worthy of life! Scream at me like I&rsquo;m screaming at you! Remind me of the unimaginable suffering I caused to those around me! Tell me those who locked me outside of time were right! Because if they weren&rsquo;t - if there really is no reason, if it&rsquo;s all by chance - then I cannot find peace. <br>
                <br>The red book stays silent. It&rsquo;s the hatch that speaks. Someone is knocking. Maybe someone survived the universe&rsquo;s fate. Maybe the Loquacious Cat changed his mind. Maybe another inmate found a way to escape. But who could possibly be knocking here, where nothing remains? I fear that outside, there is no one. I fear that I am the one knocking. I fear that answering this call would be a grave mistake. <br>
                <br>The LED lamp has stopped flooding the room with its light. The books dance around the room among the crumbs of rations. Without even realizing it, I&rsquo;m inside a Klein bottle.<br>`
    }
}